.TH STR_COUNT_WORDS 3 "2026" "libmyutils" "Library Functions Manual"
.SH NAME
str_count_words \- count words in a string
.SH SYNOPSIS
.B #include "mystrfunctions.h"
.sp
.BI "int str_count_words(const char *" str );
.SH DESCRIPTION
Counts the number of whitespace-separated words in the
null-terminated string
.IR str .
.SH RETURN VALUE
Returns the number of words found in the string.
.SH EXAMPLE
.nf
int n = str_count_words("this is a test");  // n is 4
.fi
